######## Set Spotify Volume ############
- alias: Set Spotify Volume
  trigger:
    platform: state
    entity_id: input_number.spotify_volume
  action:
    service: media_player.volume_set
    data_template:
      entity_id: media_player.spotify
      volume_level: '{{  states.input_number.spotify_volume.state  }}'
########## Telegram Temperature Command ###########
- alias: telegram_temperature
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /temperature
  action:
    service: notify.telegram_push
    data:
      title: '*Temperature*'
      message: 'BME280 {{states.sensor.temperature.state}} °C

                DS18B20 {{states.sensor.temperature_external.state}} °C

                Humidity {{states.sensor.humidity.state}} %

                Air Pressure {{states.sensor.pressure.state}} hPa'
########### Telegram Ping Command #############
- alias: Telegram bot that reply ping
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /ping
  action:
    service: notify.telegram_push
    data:
      title: '*Ping*'
      message: '{{states.sensor.speedtest_ping.state}} Sec'
############# Rain Telegram Notifications ############
- alias: rain_notification
  trigger:
    platform: numeric_state
    entity_id: sensor.dark_sky_precip_probability
    above: 70
  action:
    data:
      message: Forse piove!
      data:
        photo:
          file: /home/homeassistant/.homeassistant/files/rain.jpg
          caption: Forse piove! Prendi l'ombrello!
    service: notify.telegram_push
############# Hass Shutdown Telegram Notifications ############
- alias: shutdown_notification
  trigger:
    platform: event
    event_type: homeassistant_stop
  action:
    service: notify.telegram_push
    data:
      title: "*Home Assistant*"
      message: "❌Home Assistant has stopped at {{ as_timestamp(now()) | timestamp_custom('%H:%M', true) }}"
############# Hass Update Telegram Notifications ######################
- alias: update_notification
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.ha_github_version
  condition:
  #  - condition: template
  #    value_template: >-
  #      {{ trigger.to_state.state }}
    - condition: template
      value_template: >-
        {{ trigger.to_state.state != states('sensor.ha_version') }}
    - condition: template
      value_template: >-
        {{ trigger.to_state.state != 'unknown' }}
  action:
    - service: notify.telegram_push
      data_template:
        message: >-
          Home Assistant {{ trigger.to_state.state }} is now available on [Github](https://github.com/home-assistant/home-assistant/releases/tag/{{ trigger.to_state.state }}).
    - service: notify.html5
      data_template:
        message: >-
          Home Assistant {{ trigger.to_state.state }} is now available on {{ trigger.to_state.name.split(' ')[0] }}.
############# Hass Startup Telegram Notifications ######################
- alias: startup_notification
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: google_assistant.request_sync
    - service: automation.turn_off
      data:
        entity_id: automation.startup_notification
    - service: notify.telegram_push
      data_template:
        message: >-
          {% set message = [
            "\ud83c\udfe1 Home Assistant was restarted at {{ as_timestamp(now()) | timestamp_custom('%H:%M', true) }}",
            "\ud83c\udfe1 Home Assistant online at {{ as_timestamp(now()) | timestamp_custom('%H:%M', true) }}",
            "✅Home Assistant has (re)started at {{ as_timestamp(now()) | timestamp_custom('%H:%M', true) }}"
          ] %}
          {{ message|random }}
############# Forward Persistent Notification Telegram Notifications ######################
- alias: forward_persistent_notifications
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: call_service
      event_data:
        domain: persistent_notification
        service: create
  action:
    - service: notify.telegram_push
      data_template:
        title: >-
          {% set title = trigger.event.data.service_data.title %}
          *{{ title }}*
        message: >-
          {% set message = trigger.event.data.service_data.message %}
          {{ message }}
############# Telegram Restart Command ######################
- alias: telegram_restart
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: /restart
  action:
    - service: notify.telegram_push
      data:
        message: "Restarting Home Assistant, please wait..."
    - service: homeassistant.restart
############# Tasmota Update Telegram Notifications ######################
- alias: tasmota_update_notification
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.tasmota_github_version_parsed
  condition:
  #  - condition: template
  #    value_template: >-
  #      {{ trigger.to_state.state }}
    - condition: template
      value_template: >-
        {{ trigger.to_state.state != states('sensor.sonoff_1_tasmota_version') }}
    - condition: template
      value_template: >-
        {{ trigger.to_state.state != states('sensor.sonoff_2_tasmota_version') }}
    - condition: template
      value_template: >-
        {{ trigger.to_state.state != states('sensor.sonoff_pow_tasmota_version') }}
    - condition: template
      value_template: >-
        {{ trigger.to_state.state != 'unknown' }}
  action:
    - service: notify.telegram_push
      data_template:
        message: >-
          Tasmota {{ trigger.to_state.state }} is now available on [Github](https://github.com/arendst/Sonoff-Tasmota/releases/tag/v{{ trigger.to_state.state }}).
    - service: notify.html5
      data_template:
        message: >-
          Tasmota {{ trigger.to_state.state }} is now available on {{ trigger.to_state.name.split(' ')[0] }}.
################ Ssl Cert Telegram Reminder #####################
- alias: ssl_notification
  trigger:
    platform: numeric_state
    entity_id: sensor.homeassistant_ssl_certificate
    below: 5
  action:
    service: notify.telegram_push
    data:
      title: "*Home Assistant*"
      message: >-
        Remain {{states.sensor.homeassistant_ssl_certificate.state}} days before the SSL certificate expires.
############# Failed Login Telegram Notification ##################
- alias: login_failed_attempt
  trigger:
    platform: event
    event_type: call_service
    event_data:
      domain: persistent_notification
      service: create
  action:
    - service: notify.telegram_push
      data_template:
        message: >-
            {% set message = trigger.event.data.service_data.message %}
            {% if 'invalid authentication' in message or 'login attempts' in message %}
              {{ message }}: [Ip-Tracking](http://www.ip-tracker.org/locator/ip-lookup.php?ip={{ message.split('from ')[1] }})
            {% else %}
              {{ message }}
            {% endif %}
